Repository S-O-O-P/S-O-O-P-BackEnd-Admin, pull requests merged in 2024-07, with the labels that each got.

#2 [FEATURE][ADMIN][DASHBOARD] 대시보드 & 회원관리 & 1:1문의& 허니팟 관리 백엔드 데이터
  build.gradle
  src/main/java/com/soop/pages/config/SoopFinalProjectAdminApplication.java
  src/main/java/com/soop/pages/config/WebConfig.java
  src/main/java/com/soop/pages/customer/controller/CustomerController.java
  src/main/java/com/soop/pages/customer/controller/sampleController.java
  src/main/java/com/soop/pages/customer/model/dao/CustomerMapper.java
  src/main/java/com/soop/pages/customer/model/dao/SampleMapper.java
  src/main/java/com/soop/pages/customer/model/dto/LinkBeeUserDTO.java
  src/main/java/com/soop/pages/customer/model/dto/SampleDTO.java
  src/main/java/com/soop/pages/customer/model/service/CustomerService.java
  src/main/java/com/soop/pages/customer/model/service/SampleService.java
  src/main/java/com/soop/pages/dashboard/controller/DashboardController.java
  src/main/java/com/soop/pages/dashboard/controller/sampleController.java
  src/main/java/com/soop/pages/dashboard/model/dao/DashboardMapper.java
  src/main/java/com/soop/pages/dashboard/model/dao/SampleMapper.java
  src/main/java/com/soop/pages/dashboard/model/dto/HoneypotDTO.java
  src/main/java/com/soop/pages/dashboard/model/dto/InquiryAndMemberDTO.java
  src/main/java/com/soop/pages/dashboard/model/dto/InquiryDTO.java
  src/main/java/com/soop/pages/dashboard/model/dto/InterestDTO.java
  src/main/java/com/soop/pages/dashboard/model/dto/MemberDTO.java
  src/main/java/com/soop/pages/dashboard/model/dto/NoticeAndMemberDTO.java
  src/main/java/com/soop/pages/dashboard/model/dto/NoticeDTO.java
  src/main/java/com/soop/pages/dashboard/model/dto/PostHoneyAndRelatedDTO.java
  src/main/java/com/soop/pages/dashboard/model/dto/TicketDTO.java
  src/main/java/com/soop/pages/dashboard/model/service/DashboardService.java
  src/main/java/com/soop/pages/dashboard/model/service/SampleService.java
  src/main/java/com/soop/pages/honeypot/controller/HoneypotController.java
  src/main/java/com/soop/pages/honeypot/controller/sampleController.java
  src/main/java/com/soop/pages/honeypot/model/dao/HoneypotMapper.java
  src/main/java/com/soop/pages/honeypot/model/dao/SampleMapper.java
  src/main/java/com/soop/pages/honeypot/model/dto/HoneypotDTO.java
  src/main/java/com/soop/pages/honeypot/model/dto/SampleDTO.java
  src/main/java/com/soop/pages/honeypot/model/service/HoneypotService.java
  src/main/java/com/soop/pages/honeypot/model/service/SampleService.java
  src/main/java/com/soop/pages/inquiry/controller/InquiryController.java
  src/main/java/com/soop/pages/inquiry/model/dao/InquiryMapper.java
  src/main/java/com/soop/pages/inquiry/model/dto/InquiryDTO.java
  src/main/java/com/soop/pages/inquiry/model/service/InquiryService.java
  src/main/java/com/soop/pages/login/controller/LoginController.java
  src/main/java/com/soop/pages/login/model/dao/LoginMapper.java
  src/main/java/com/soop/pages/login/model/dto/LinkBeeUserDTO.java
  src/main/java/com/soop/pages/login/model/service/LoginService.java
  src/main/resources/mapper/CustomerMapper.xml
  src/main/resources/mapper/DashboardMapper.xml
  src/main/resources/mapper/HoneypotMapper.xml
  src/main/resources/mapper/InquiryMapper.xml
  src/main/resources/mapper/LoginMapper.xml
Labels: ✨ Feature

#6 [FEATURE][ADMIN][DASHBOARD2] ANSWER_DATE 등록
  src/main/java/com/soop/pages/inquiry/controller/InquiryController.java
  src/main/java/com/soop/pages/inquiry/model/dao/InquiryMapper.java
  src/main/java/com/soop/pages/inquiry/model/service/InquiryService.java
  src/main/resources/mapper/InquiryMapper.xml
Labels: ✨ Feature

#7 [FEATURE][CULTUREINFO]얼리버드 공연/전시 정보 조회
  src/main/java/com/soop/pages/config/SoopFinalProjectAdminApplication.java
  src/main/java/com/soop/pages/cultureInfo/controller/CultureInfoController.java
  src/main/java/com/soop/pages/cultureInfo/controller/sampleController.java
  src/main/java/com/soop/pages/cultureInfo/model/dao/CultureInfoMapper.java
  src/main/java/com/soop/pages/cultureInfo/model/dao/SampleMapper.java
  src/main/java/com/soop/pages/cultureInfo/model/dto/CultureInfoDTO.java
  src/main/java/com/soop/pages/cultureInfo/model/dto/SampleDTO.java
  src/main/java/com/soop/pages/cultureInfo/model/service/CultureInfoService.java
  src/main/java/com/soop/pages/cultureInfo/model/service/SampleService.java
  src/main/resources/mapper/CultureInfoMapper.xml
Labels: ✨ Feature

#10 [FEATURE][ADMIN][DASHBOARD3] 로그인 수정
  src/main/java/com/soop/pages/login/controller/LoginController.java
  src/main/java/com/soop/pages/login/model/dao/LoginMapper.java
  src/main/java/com/soop/pages/login/model/dto/LinkBeeUserDTO.java
  src/main/java/com/soop/pages/login/model/dto/LoginAndLinkBeeUserDTO.java
  src/main/java/com/soop/pages/login/model/service/LoginService.java
  src/main/resources/mapper/HoneypotMapper.xml
  src/main/resources/mapper/LoginMapper.xml
Labels: ✨ Feature

#12 [FEATURE][CULTUREINFO] 얼리버드 공연/전시 정보 Mapper.xml 에러 발생으로 인한 수정
  src/main/resources/mapper/CultureInfoMapper.xml
Labels: 🐞 BugFix, ✨ Feature

#13 [FEATURE][NOTICEREGIST] 공지사항 작성페이지
  http/notice.http
  src/main/java/com/soop/pages/notice/controller/Notice.java
  src/main/java/com/soop/pages/notice/controller/sampleController.java
  src/main/java/com/soop/pages/notice/model/dao/NoticeMapper.java
  src/main/java/com/soop/pages/notice/model/dao/SampleMapper.java
  src/main/java/com/soop/pages/notice/model/dto/FileDTO.java
  src/main/java/com/soop/pages/notice/model/dto/NoticeFileDTO.java
  src/main/java/com/soop/pages/notice/model/dto/SampleDTO.java
  src/main/java/com/soop/pages/notice/model/service/NoticeService.java
  src/main/java/com/soop/pages/notice/model/service/SampleService.java
  src/main/resources/mapper/NoticeRegist.xml
Labels: ✨ Feature

#16 [FEATURE][ADMIN][DASHBOARD9] 공지사항 수정
  src/main/java/com/soop/pages/notice/controller/Notice.java
  src/main/java/com/soop/pages/notice/model/dao/NoticeMapper.java
  src/main/java/com/soop/pages/notice/model/dto/NoticeFileDTO.java
  src/main/java/com/soop/pages/notice/model/service/NoticeService.java
  src/main/resources/mapper/NoticeRegist.xml
Labels: ✨ Feature

#14 [FEATURE][CULTUREINFO] 얼리버드 공연/전시 정보 Mapper.xml 에러 발생으로 인한 재수정
  src/main/resources/mapper/CultureInfoMapper.xml
Labels: 🐞 BugFix, ✨ Feature

#21 [FEATURE][NOTICE] 공지사항 url 변경, 수정 디테일 페이지
  http/notice.http
  src/main/java/com/soop/pages/notice/controller/Notice.java
  src/main/java/com/soop/pages/notice/model/dao/NoticeMapper.java
  src/main/java/com/soop/pages/notice/model/dto/MemberDTO.java
  src/main/java/com/soop/pages/notice/model/dto/NoticeMemberFileDTO.java
  src/main/java/com/soop/pages/notice/model/service/NoticeService.java
  src/main/resources/mapper/Notice.xml
Labels: 📬 API, ✨ Feature

#20 [FEATURE][ADMIN][DASHBOARD5] 공지사항
  src/main/resources/mapper/DashboardMapper.xml
Labels: :pager: BackEnd, ✨ Feature

#22 [FEATURE][NOTICE] 공지사항 수정, 삭제 기능
  http/notice.http
  src/main/java/com/soop/pages/notice/controller/Notice.java
  src/main/java/com/soop/pages/notice/model/dao/NoticeMapper.java
  src/main/java/com/soop/pages/notice/model/dto/FileDTO.java
  src/main/java/com/soop/pages/notice/model/service/NoticeService.java
  src/main/resources/mapper/Notice.xml
Labels: :pager: BackEnd, ✨ Feature

#23 [FEATURE][NOTICE] FILE 업로드
  src/main/java/com/soop/pages/dashboard/model/dto/NoticeDTO.java
  src/main/java/com/soop/pages/notice/controller/Notice.java
  src/main/java/com/soop/pages/notice/model/dao/NoticeMapper.java
  src/main/java/com/soop/pages/notice/model/dto/NoticeMemberFileDTO.java
  src/main/java/com/soop/pages/notice/model/service/NoticeService.java
  src/main/resources/mapper/Notice.xml
Labels: :pager: BackEnd, ✨ Feature

#25 [FEATURE] [NOTICE] FILE 등록, 삭제, 조회 기능 추가
  src/main/java/com/soop/pages/notice/controller/Notice.java
  src/main/java/com/soop/pages/notice/model/dao/NoticeMapper.java
  src/main/java/com/soop/pages/notice/model/dto/NoticeDTO.java
  src/main/java/com/soop/pages/notice/model/service/NoticeService.java
  src/main/resources/mapper/Notice.xml
  src/main/resources/static/uploadImages/0195e0d7-a63d-4a14-8e55-9430d4def5d8.jpg
  src/main/resources/static/uploadImages/06b0534b-711c-44d9-bbdd-18a71433e1e2.jpg
  src/main/resources/static/uploadImages/f3ea6316-ea27-4fb5-bd45-263221ad83d2.jpg
Labels: :pager: BackEnd, ✨ Feature

#27 [FEATURE][FILEEDIT] 공지사항 파일 수정
  src/main/java/com/soop/pages/notice/controller/Notice.java
  src/main/java/com/soop/pages/notice/model/dao/NoticeMapper.java
  src/main/java/com/soop/pages/notice/model/service/NoticeService.java
  src/main/resources/mapper/Notice.xml
  src/main/resources/static/uploadImages/2e0560fc-da9a-4ae2-95c2-400404141b0e.png
  src/main/resources/static/uploadImages/df3cf34f-4603-48e7-802d-ab2c3e58c673.png
Labels: :pager: BackEnd, ✨ Feature

#28 [FEATURE][ADMIN][DASHBOARD7] 로그인 수정
  build.gradle
  src/main/java/com/soop/CustomErrorController.java
  src/main/java/com/soop/pages/config/GlobalExceptionHandler.java
  src/main/java/com/soop/pages/config/WebConfig.java
  src/main/java/com/soop/pages/login/controller/LoginController.java
  src/main/resources/static/css/Commons.css
  src/main/resources/static/img/logo.png
  src/main/resources/templates/400.html
  src/main/resources/templates/403.html
  src/main/resources/templates/404.html
  src/main/resources/templates/500.html
  src/main/resources/templates/error.html
Labels: :pager: BackEnd

#31 [FEATURE][ADMIN][DASHBOARD8] 백엔드 예외 처리
  src/main/java/com/soop/CustomErrorController.java
  src/main/java/com/soop/pages/config/GlobalExceptionHandler.java
  src/main/java/com/soop/pages/config/WebConfig.java
  src/main/resources/application.properties
  src/main/resources/templates/400.html
  src/main/resources/templates/403.html
  src/main/resources/templates/404.html
  src/main/resources/templates/error.html
Labels: :pager: BackEnd, ✨ Feature

#34 [FEATURE][NOTICE] 공지사항 이미지 파이어베이스
  build.gradle
  src/main/java/com/soop/pages/firebase/config/FirebaseConfig.java
  src/main/java/com/soop/pages/firebase/service/FileUploadService.java
  src/main/java/com/soop/pages/notice/controller/Notice.java
Labels: 🔨 Refactor

#36 [FEATURE][CULTUREINFO][SWAGGER] 공연/전시 정보 REST API - SWAGGER 등록 작업
  build.gradle
  src/main/java/com/soop/pages/cultureInfo/controller/CultureInfoController.java
  src/main/java/com/soop/swagger/SwaggerConfig.java
  src/main/resources/application.yml
Labels: 📬 API, :pager: BackEnd, ✨ Feature

#38 [FEATURE][ADMIN][DASHBOARD9] 에러페이지 버튼 추가
  src/main/java/com/soop/pages/config/WebConfig.java
  src/main/java/com/soop/pages/dashboard/model/dto/HoneypotDTO.java
  src/main/java/com/soop/pages/dashboard/model/dto/InquiryDTO.java
  src/main/java/com/soop/pages/dashboard/model/dto/NoticeDTO.java
  src/main/java/com/soop/pages/dashboard/model/service/DashboardService.java
  src/main/java/com/soop/pages/honeypot/model/dto/HoneypotDTO.java
  src/main/java/com/soop/pages/honeypot/model/service/HoneypotService.java
  src/main/java/com/soop/pages/inquiry/model/dto/InquiryDTO.java
  src/main/java/com/soop/pages/inquiry/model/service/InquiryService.java
  src/main/java/com/soop/pages/notice/model/dto/NoticeDTO.java
  src/main/java/com/soop/pages/notice/model/dto/NoticeMemberFileDTO.java
  src/main/java/com/soop/pages/notice/model/service/NoticeService.java
  src/main/resources/mapper/DashboardMapper.xml
  src/main/resources/mapper/HoneypotMapper.xml
  src/main/resources/mapper/InquiryMapper.xml
  src/main/resources/mapper/Notice.xml
  src/main/resources/static/css/Commons.css
  src/main/resources/static/uploadImages/60f5fbfd-2cbd-4238-a4d9-d2e4880e53f4.png
  src/main/resources/static/uploadImages/8dc10751-739a-4f60-a8c5-66ced18d03c1.png
  src/main/resources/static/uploadImages/c470084e-8931-4628-8e5c-189b56dfa482.png
  src/main/resources/templates/400.html
  src/main/resources/templates/403.html
  src/main/resources/templates/404.html
  src/main/resources/templates/500.html
  src/main/resources/templates/error.html
Labels: :pager: BackEnd, ✨ Feature

#40 [FEATURE][SWAGGER][API] 관리자 REST API - SWAGGER 등록 작업
  src/main/java/com/soop/pages/customer/controller/CustomerController.java
  src/main/java/com/soop/pages/dashboard/controller/DashboardController.java
  src/main/java/com/soop/pages/honeypot/controller/HoneypotController.java
  src/main/java/com/soop/pages/inquiry/controller/InquiryController.java
  src/main/java/com/soop/pages/login/controller/LoginController.java
  src/main/java/com/soop/pages/notice/controller/Notice.java
Labels: 📬 API, :pager: BackEnd, ✨ Feature

#42 [FEATURE][ADMIN][DASHBOARD10] 예외처리 수정
  src/main/java/com/soop/CustomErrorController.java
  src/main/java/com/soop/pages/config/ForbiddenException.java
  src/main/java/com/soop/pages/config/GlobalExceptionHandler.java
  src/main/resources/application.properties
  src/main/resources/application.yml
  src/main/resources/mapper/HoneypotMapper.xml
  src/main/resources/static/css/Commons.css
  src/main/resources/static/img/logo.png
  src/main/resources/templates/400.html
  src/main/resources/templates/403.html
  src/main/resources/templates/404.html
  src/main/resources/templates/500.html
  src/main/resources/templates/error.html
Labels: :pager: BackEnd, ✨ Feature

#43 [develop] port 8082 변경
  src/main/java/com/soop/pages/config/WebConfig.java
  src/main/resources/application.yml
Labels: 📬 API, 🌏 Deploy

#45 [FEATURE][ADMIN][DASHBOARD11] 예외처리 수정
  src/main/java/com/soop/pages/config/GlobalExceptionHandler.java
Labels: :pager: BackEnd, ✨ Feature

#46 [FEATURE][NOTICE] 정렬 변경
  src/main/resources/mapper/Notice.xml
Labels: :pager: BackEnd

#47 [FEATURE][ADMIN][DASHBOARD12] 대시보드 최신 공지사항 DATE 수정
  src/main/java/com/soop/pages/dashboard/model/dto/NoticeDTO.java
Labels: :pager: BackEnd, ✨ Feature

#49 [HOTFIX] 날짜 형식 변경
  src/main/java/com/soop/pages/customer/model/dto/LinkBeeUserDTO.java
  src/main/java/com/soop/pages/dashboard/model/dto/HoneypotDTO.java
  src/main/java/com/soop/pages/dashboard/model/dto/NoticeDTO.java
  src/main/java/com/soop/pages/honeypot/model/dto/HoneypotDTO.java
Labels: 🐞 BugFix, ✅ Test

#50 날짜 포맷 변경
  src/main/java/com/soop/pages/inquiry/model/dto/InquiryDTO.java
Labels: :pager: BackEnd
